### ISSUE TITLE
Something wrong with API

### ISSUE THREAD

**Issue by riartem** [blockchain/api-v1-client-php#18]
Hello, dear developers.
I've connected to Blockchain API and did some tests:
1. Register new wallet (success) 19YVpCqUR3JkiNBqozGxoBFej28utodMrb
2. Register receive address with callback (success) 12tZWJCC3wLeXF2rvs9Kaq8bVtt8jgpgWx
3. Send test payment 0.004479 BTC to receive address (success) Hash: https://blockchain.info/tx/f07708e3dfe5dd00ba62b1ac124419174af6365a74578b0e34fb6d4528f21b58

Complete results: 
- When I entered to new wallet throught web interface, I don't see receive adress from step 2.
- Receive address do not redirected payment to new wallet address

How to make it works?

contact email: riartem[at]gmail.com

**Comment by KMHouk** [comment]
Hi,

Is this is issue with the PHP client library, or the receive payments API?

**Comment by riartem** [comment]
Problem with API (library works correctly, thanks!).
But I don't know any developers contacts, therefore write here.
Problem in the api/receive method.
I send api_key, method (create) and address (destination).
It returns json object
{
    "input_address": "12QjLh3XXFyCs2X9UTNVqAyeBwVq69Rd4d",
    "destination": "19YVpCqUR3JkiNBqozGxoBFej28utodMrb",
    "fee_percent": 0
}
But if I login in the web wallet https://blockchain.info/wallet/ no new addresses in the "Receive money" tab.
Help me, please.

**Comment by clarkmoody** [comment]
The receive API endpoint does not add addresses to your wallet. Rather, it forwards all funds send to the `input_address` to the `destination` address you specified.

**Comment by riartem** [comment]
I understood, but. If you read my first message no money redirect here :(
You can check it by transaction: https://blockchain.info/tx/f07708e3dfe5dd00ba62b1ac124419174af6365a74578b0e34fb6d4528f21b58
I send some money to new generated "input address" and money still on "input address".
Destination address is empty (no money): https://blockchain.info/address/19YVpCqUR3JkiNBqozGxoBFej28utodMrb
And I have no access to that "input" address to operate with that money. Thay are in /dev/null apparently..

**Comment by clarkmoody** [comment]
I believe this is an issue with the API itself, not the PHP client library. I have forwarded this issue to the dev team.

**Comment by riartem** [comment]
Thank you very much!

**Comment by KMHouk** [comment]
Hey, 

This issue should be solved now. Sorry for the inconvenience!

-Kevin

**Comment by riartem** [comment]
Yes, yesterday issue solved, but when I created new wallet (1B9rMHLq9g9W41SL1MRbHkhQkqC6LnQSTs) with new redirect address (1FjVouQ34NrvckjopF7konEGYTgKgBeAdV) I have the same trouble. Something still wrong..

**Comment by KMHouk** [comment]
The minimum supported amount is .0005 BTC to a forwarding address. 

Please open a support ticket for further questions.

Best,
Kevin
